using BoilerPlate.Authentication.Database.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace BoilerPlate.Authentication.Database;

/// <summary>
///     Base authentication database context with Identity support using Guid IDs and multi-tenancy
///     This is an abstract base class that must be inherited by concrete implementations
/// </summary>
public abstract class BaseAuthDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, Guid>
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="BaseAuthDbContext" /> class
    /// </summary>
    /// <param name="options">The options to be used by a DbContext</param>
    protected BaseAuthDbContext(DbContextOptions<BaseAuthDbContext> options)
        : base(options)
    {
    }

    /// <summary>
    ///     Tenants
    /// </summary>
    public DbSet<Tenant> Tenants { get; set; } = null!;

    /// <summary>
    ///     Tenant settings
    /// </summary>
    public DbSet<TenantSetting> TenantSettings { get; set; } = null!;

    /// <summary>
    ///     Refresh tokens
    /// </summary>
    public DbSet<RefreshToken> RefreshTokens { get; set; } = null!;

    /// <summary>
    ///     OAuth2 authorization codes
    /// </summary>
    public DbSet<AuthorizationCode> AuthorizationCodes { get; set; } = null!;

    /// <summary>
    ///     OAuth2 clients
    /// </summary>
    public DbSet<OAuthClient> OAuthClients { get; set; } = null!;

    /// <summary>
    ///     User consent decisions for OAuth2 clients
    /// </summary>
    public DbSet<UserConsent> UserConsents { get; set; } = null!;

    /// <summary>
    ///     Configures the model that was discovered from the entity types
    /// </summary>
    /// <param name="builder">The builder being used to construct the model for this context</param>
    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        // Configure Tenant
        builder.Entity<Tenant>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // UUIDs are generated by application
            entity.Property(e => e.Name).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.CreatedAt).IsRequired();
            entity.HasIndex(e => e.Name).IsUnique();
        });

        // Configure ApplicationUser
        builder.Entity<ApplicationUser>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever(); // UUIDs are generated by application
            entity.Property(e => e.TenantId).IsRequired();
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.CreatedAt).IsRequired();

            // Unique indexes per tenant
            entity.HasIndex(e => new { e.TenantId, e.Email })
                .IsUnique()
                .HasFilter("[Email] IS NOT NULL");

            entity.HasIndex(e => new { e.TenantId, e.UserName })
                .IsUnique()
                .HasFilter("[UserName] IS NOT NULL");

            // Foreign key to Tenant
            entity.HasOne(e => e.Tenant)
                .WithMany()
                .HasForeignKey(e => e.TenantId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Configure ApplicationRole
        builder.Entity<ApplicationRole>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever(); // UUIDs are generated by application
            entity.Property(e => e.TenantId).IsRequired();
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.CreatedAt).IsRequired();

            // Unique role name per tenant
            entity.HasIndex(e => new { e.TenantId, e.Name })
                .IsUnique();

            // Foreign key to Tenant
            entity.HasOne(e => e.Tenant)
                .WithMany()
                .HasForeignKey(e => e.TenantId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Configure TenantSetting
        builder.Entity<TenantSetting>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // UUIDs are generated by application
            entity.Property(e => e.TenantId).IsRequired();
            entity.Property(e => e.Key).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Value).HasMaxLength(4000); // Reasonable limit for freeform text
            entity.Property(e => e.CreatedAt).IsRequired();

            // Unique constraint: TenantId + Key combination must be unique
            entity.HasIndex(e => new { e.TenantId, e.Key })
                .IsUnique();

            // Foreign key to Tenant
            entity.HasOne(e => e.Tenant)
                .WithMany()
                .HasForeignKey(e => e.TenantId)
                .OnDelete(DeleteBehavior.Cascade); // Cascade delete settings when tenant is deleted
        });

        // Configure RefreshToken
        builder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // UUIDs are generated by application
            entity.Property(e => e.UserId).IsRequired();
            entity.Property(e => e.TenantId).IsRequired();
            entity.Property(e => e.EncryptedToken).IsRequired();
            entity.Property(e => e.TokenHash).IsRequired().HasMaxLength(64); // SHA-256 hash is 64 hex characters
            entity.Property(e => e.ExpiresAt).IsRequired();
            entity.Property(e => e.IsUsed).IsRequired();
            entity.Property(e => e.IsRevoked).IsRequired();
            entity.Property(e => e.CreatedAt).IsRequired();
            entity.Property(e => e.IssuedFromIpAddress).HasMaxLength(45); // IPv6 max length
            entity.Property(e => e.IssuedFromUserAgent).HasMaxLength(500);

            // Index on token hash for fast lookup
            entity.HasIndex(e => e.TokenHash)
                .IsUnique();

            // Index on user ID and tenant for querying user's tokens
            entity.HasIndex(e => new { e.UserId, e.TenantId });

            // Index on expiration for cleanup queries
            entity.HasIndex(e => e.ExpiresAt);

            // Foreign key to ApplicationUser
            entity.HasOne(e => e.User)
                .WithMany()
                .HasForeignKey(e => e.UserId)
                .OnDelete(DeleteBehavior.Cascade); // Cascade delete tokens when user is deleted

            // Foreign key to Tenant
            entity.HasOne(e => e.Tenant)
                .WithMany()
                .HasForeignKey(e => e.TenantId)
                .OnDelete(DeleteBehavior.Restrict); // Don't delete tokens if tenant is deleted (keep for audit)
        });

        // Configure AuthorizationCode
        builder.Entity<AuthorizationCode>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Code).IsRequired()
                .HasMaxLength(500); // Base64URL encoded code with room for future enhancements
            entity.Property(e => e.UserId).IsRequired();
            entity.Property(e => e.TenantId).IsRequired();
            entity.Property(e => e.ClientId).IsRequired().HasMaxLength(200);
            entity.Property(e => e.RedirectUri).IsRequired().HasMaxLength(500);
            entity.Property(e => e.Scope).HasMaxLength(500);
            entity.Property(e => e.State).HasMaxLength(500);
            entity.Property(e => e.CodeChallenge).HasMaxLength(200);
            entity.Property(e => e.CodeChallengeMethod).HasMaxLength(10);
            entity.Property(e => e.ExpiresAt).IsRequired();
            entity.Property(e => e.IsUsed).IsRequired();
            entity.Property(e => e.CreatedAt).IsRequired();
            entity.Property(e => e.IssuedFromIpAddress).HasMaxLength(45);
            entity.Property(e => e.IssuedFromUserAgent).HasMaxLength(500);

            // Index on code for fast lookup
            entity.HasIndex(e => e.Code).IsUnique();

            // Index on expiration for cleanup queries
            entity.HasIndex(e => e.ExpiresAt);

            // Index on user ID and tenant
            entity.HasIndex(e => new { e.UserId, e.TenantId });

            // Foreign key to ApplicationUser
            entity.HasOne(e => e.User)
                .WithMany()
                .HasForeignKey(e => e.UserId)
                .OnDelete(DeleteBehavior.Cascade);

            // Foreign key to Tenant
            entity.HasOne(e => e.Tenant)
                .WithMany()
                .HasForeignKey(e => e.TenantId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Configure OAuthClient
        builder.Entity<OAuthClient>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ClientId).IsRequired().HasMaxLength(200);
            entity.Property(e => e.ClientSecretHash).HasMaxLength(500);
            entity.Property(e => e.Name).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.RedirectUris).IsRequired().HasMaxLength(2000);
            entity.Property(e => e.IsConfidential).IsRequired();
            entity.Property(e => e.IsActive).IsRequired();
            entity.Property(e => e.CreatedAt).IsRequired();

            // Unique client ID
            entity.HasIndex(e => e.ClientId).IsUnique();

            // Index on tenant ID
            entity.HasIndex(e => e.TenantId);

            // Foreign key to Tenant (optional)
            entity.HasOne(e => e.Tenant)
                .WithMany()
                .HasForeignKey(e => e.TenantId)
                .OnDelete(DeleteBehavior.SetNull); // Set to null if tenant is deleted
        });

        // Configure UserConsent
        builder.Entity<UserConsent>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.UserId).IsRequired();
            entity.Property(e => e.TenantId).IsRequired();
            entity.Property(e => e.ClientId).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Scope).HasMaxLength(1000);
            entity.Property(e => e.GrantedAt).IsRequired();
            entity.Property(e => e.LastConfirmedAt).IsRequired();

            // Index on user and client for fast lookup
            entity.HasIndex(e => new { e.UserId, e.ClientId });

            // Index on tenant
            entity.HasIndex(e => e.TenantId);

            // Index on expiration for cleanup queries
            entity.HasIndex(e => e.ExpiresAt);

            // Foreign key to ApplicationUser
            entity.HasOne(e => e.User)
                .WithMany()
                .HasForeignKey(e => e.UserId)
                .OnDelete(DeleteBehavior.Cascade);

            // Foreign key to Tenant
            entity.HasOne(e => e.Tenant)
                .WithMany()
                .HasForeignKey(e => e.TenantId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Configure Identity tables naming
        builder.Entity<IdentityUserRole<Guid>>().ToTable("UserRoles");
        builder.Entity<IdentityUserClaim<Guid>>().ToTable("UserClaims");
        builder.Entity<IdentityUserLogin<Guid>>().ToTable("UserLogins");
        builder.Entity<IdentityUserToken<Guid>>().ToTable("UserTokens");
        builder.Entity<IdentityRoleClaim<Guid>>().ToTable("RoleClaims");
    }
}