using BoilerPlate.Authentication.Database.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace BoilerPlate.Authentication.Database;

/// <summary>
/// Base authentication database context with Identity support using Guid IDs and multi-tenancy
/// </summary>
public class BaseAuthDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, Guid>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="BaseAuthDbContext"/> class
    /// </summary>
    /// <param name="options">The options to be used by a DbContext</param>
    public BaseAuthDbContext(DbContextOptions<BaseAuthDbContext> options)
        : base(options)
    {
    }

    /// <summary>
    /// Tenants
    /// </summary>
    public DbSet<Tenant> Tenants { get; set; } = null!;

    /// <summary>
    /// Tenant settings
    /// </summary>
    public DbSet<TenantSetting> TenantSettings { get; set; } = null!;

    /// <summary>
    /// Configures the model that was discovered from the entity types
    /// </summary>
    /// <param name="builder">The builder being used to construct the model for this context</param>
    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        // Configure Tenant
        builder.Entity<Tenant>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // UUIDs are generated by application
            entity.Property(e => e.Name).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.CreatedAt).IsRequired();
            entity.HasIndex(e => e.Name).IsUnique();
        });

        // Configure ApplicationUser
        builder.Entity<ApplicationUser>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever(); // UUIDs are generated by application
            entity.Property(e => e.TenantId).IsRequired();
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.CreatedAt).IsRequired();

            // Unique indexes per tenant
            entity.HasIndex(e => new { e.TenantId, e.Email })
                .IsUnique()
                .HasFilter("[Email] IS NOT NULL");

            entity.HasIndex(e => new { e.TenantId, e.UserName })
                .IsUnique()
                .HasFilter("[UserName] IS NOT NULL");

            // Foreign key to Tenant
            entity.HasOne(e => e.Tenant)
                .WithMany()
                .HasForeignKey(e => e.TenantId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Configure ApplicationRole
        builder.Entity<ApplicationRole>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever(); // UUIDs are generated by application
            entity.Property(e => e.TenantId).IsRequired();
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.CreatedAt).IsRequired();

            // Unique role name per tenant
            entity.HasIndex(e => new { e.TenantId, e.Name })
                .IsUnique();

            // Foreign key to Tenant
            entity.HasOne(e => e.Tenant)
                .WithMany()
                .HasForeignKey(e => e.TenantId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Configure TenantSetting
        builder.Entity<TenantSetting>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedNever(); // UUIDs are generated by application
            entity.Property(e => e.TenantId).IsRequired();
            entity.Property(e => e.Key).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Value).HasMaxLength(4000); // Reasonable limit for freeform text
            entity.Property(e => e.CreatedAt).IsRequired();

            // Unique constraint: TenantId + Key combination must be unique
            entity.HasIndex(e => new { e.TenantId, e.Key })
                .IsUnique();

            // Foreign key to Tenant
            entity.HasOne(e => e.Tenant)
                .WithMany()
                .HasForeignKey(e => e.TenantId)
                .OnDelete(DeleteBehavior.Cascade); // Cascade delete settings when tenant is deleted
        });

        // Configure Identity tables naming
        builder.Entity<IdentityUserRole<Guid>>().ToTable("UserRoles");
        builder.Entity<IdentityUserClaim<Guid>>().ToTable("UserClaims");
        builder.Entity<IdentityUserLogin<Guid>>().ToTable("UserLogins");
        builder.Entity<IdentityUserToken<Guid>>().ToTable("UserTokens");
        builder.Entity<IdentityRoleClaim<Guid>>().ToTable("RoleClaims");
    }
}
